### ISSUE TITLE
Google Address Input is broken

### ISSUE THREAD

**Issue by Caseyyu2** [wix/wix-style-react#1241]
### Summary:
Navigate to Google Address Input
https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.8%20Google%20address%20input&full=0&down=0&left=1&panelRight=0.

The page is throwing exception
Cannot read property 'maps' of undefined
TypeError: Cannot read property 'maps' of undefined
    at new GoogleMapsClient (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:5505205)
    at new GoogleAddressInput (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:4613415)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:1047420)
    at ReactCompositeComponentWrapper._constructComponent (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:1047185)
    at ReactCompositeComponentWrapper.mountComponent (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:1045823)
    at Object.mountComponent (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:275260)
    at ReactDOMComponent.mountChildren (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:1038559)
    at ReactDOMComponent._createInitialChildren (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:1018545)
    at ReactDOMComponent.mountComponent (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:1015591)
    at Object.mountComponent (https://wix.github.io/wix-style-react/static/preview.624c06f317d931ba512a.bundle.js:1:275260)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
1. Navigate to Google Address Input
https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.8%20Google%20address%20input&full=0&down=0&left=1&panelRight=0.

### Expected behavior:
The page is not broken

**Comment by argshook** [comment]
@Caseyyu2 thanks for reporting!
i fixed that page, let me know if you see anything else not working :)
