### ISSUE TITLE
Tooltip  - crashes with 'firstChild' on server-side rendering

### ISSUE THREAD

**Issue by oded-soffrin** [wix/wix-style-react#335]
I used the tooltip in my project (pro-gallery-shop-server)
if I don't specify 'active={false}' the server crashes
FYI

TypeError: Cannot read property 'firstChild' of undefined
    at Object.ReactMount.findComponentRoot (/Users/odeds/Work/pro-gallery-shop-server/node_modules/react/lib/ReactMount.js:715:39)
    at Object.ReactMount.findReactNodeByID (/Users/odeds/Work/pro-gallery-shop-server/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/Users/odeds/Work/pro-gallery-shop-server/node_modules/react/lib/ReactMount.js:162:32)

**Comment by lbelinsk** [comment]
@oded-soffrin is this still happening?

**Comment by oded-soffrin** [comment]
Sorry @lbelinsk , haven't seen your comment up until now
I don't know if it's still happening, can check if needed

**Comment by shlomitc** [comment]
Please recheck and re-open if needed. Thanks!
